package tn.esprit;


import com.codename1.db.Cursor;
import com.codename1.db.Database;
import com.codename1.io.FileSystemStorage;
import com.codename1.io.Log;
import com.codename1.io.Util;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Display;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;


import tn.esprit.entite.Utilisateur;
import tn.esprit.profil.BaseDD;
import tn.esprit.profil.LoginForm;


/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class Main {

    
    private Form current;
    private Resources theme;
    private static Utilisateur loggedUser;
    private static Database DB=null;
    
    public void init(Object context) {      
        theme = UIManager.initFirstTheme("/theme");        
        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);
        Toolbar.setCenteredDefault(false);
        
    }
    
    public void start() {
       
            if(current != null){
                current.show();
                return;
            }
                   
        new LoginForm(theme).show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }
   

}
