package tn.esprit;

import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Display;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Toolbar;
import com.codename1.util.EasyThread;
import java.util.ArrayList;
import tn.esprit.entite.Article;
import tn.esprit.entite.Utilisateur;
import tn.esprit.profil.LoginForm;
import tn.esprit.services.BlogService;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class Main {

    private Form current;
    private Resources theme;
    public boolean firstRun = true;
    public ArrayList<Article> oldList;
    private static Utilisateur loggedUser;

    public void init(Object context) {
        // use two network threads instead of one
        //updateNetworkThreadCount(2);
        theme = UIManager.initFirstTheme("/theme");
        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);
        Toolbar.setCenteredDefault(false);

    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }
        BlogService bS = new BlogService();
        Display.getInstance().callSerially(new Runnable() {
            public void run() {
                while (true) {
                        System.out.println("Tik!");
                        if (firstRun) {
                            System.out.println("First run");
                            oldList = bS.findAll();
                            
                            firstRun = false;
                        } else {
                            System.out.println("Not first run!" + bS.findAll().size() + " " + oldList.size());
                            if (oldList.size() < bS.findAll().size()) {
                                int diff = Math.abs(oldList.size() - bS.findAll().size());
                                Dialog.show("Notification", "Il y'a " + diff + " article" + (diff > 1 ? "s" : "") +
                                        ", consulter le blog!", "Hide", null);
                                oldList = bS.findAll();
                            }
                        }
                   
                }
            }
        });
        new LoginForm(theme).show();
    }

    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }

}
